const SUCCESS_CODE = 200;
const CREATED_CODE = 201;
const BAD_REQUEST_CODE = 400;
const UNAUTHORIZED_CODE = 401;
const NOT_FOUND_CODE = 404;
const CONFLICT_CODE = 409;
const VALIDATION_ERROR_CODE = 422;
const FORBIDDEN_CODE = 403;

module.exports = {
    SUCCESS_CODE,
    CREATED_CODE,
    BAD_REQUEST_CODE,
    UNAUTHORIZED_CODE,
    NOT_FOUND_CODE,
    CONFLICT_CODE,
    VALIDATION_ERROR_CODE,
    FORBIDDEN_CODE
}